import {
  // Accessibility
  Accessibility, Eye, EyeOff, Hand, Ear, MousePointer, Pointer, PersonStanding, Move, ZoomIn, ZoomOut,
  // Accounts & access
  Key, Lock, LockOpen, Shield, ShieldCheck, ShieldAlert, ShieldX, LogIn, LogOut, KeyRound, Scan,
  // Animals
  Bird, Cat, Dog, Fish, Rabbit, Bug, Turtle, Snail, Squirrel, Worm,
  // Arrows
  ArrowUp, ArrowDown, ArrowLeft, ArrowRight, ArrowUpRight, ArrowDownLeft,
  ArrowLeftRight, ArrowUpDown, RotateCw, RefreshCw, ChevronsUp, ChevronsDown, ChevronUp, ChevronDown,
  // Buildings
  Building2, Building, School, Hospital, Warehouse, Factory, Store, Landmark, Home, Castle, Church, Tent,
  // Charts
  BarChart3, PieChart, TrendingUp, TrendingDown, Activity, LineChart, Sigma, Percent, Hash,
  // Communication
  MessageSquare, MessageCircle, Mail, Phone, Send, Bell, Megaphone, Mic, Globe, Link, PhoneCall, AtSign,
  // Connectivity
  Wifi, WifiOff, Bluetooth, BluetoothConnected, Signal, Router, Nfc, Share2,
  // Cursors
  MousePointer2, Crosshair, Grab,
  // Design
  Palette, Paintbrush, Pen, PenTool, Pencil, Scissors, Ruler, Layers, Wand2, Eraser, Pipette, Crop,
  // Coding & development
  Code, Code2, Terminal, GitBranch, GitCommit, GitMerge, GitPullRequest, Webhook, Database, Server, Braces, PackageOpen,
  // Devices
  Smartphone, Tablet, Laptop, Monitor, Tv, Watch, Headphones, Keyboard, Cpu, HardDrive, Printer,
  // Emoji
  Smile, Frown, Meh, ThumbsUp, ThumbsDown, Heart, Star, Zap,
  // File icons
  File, FileText, Folder, FolderOpen, Archive, FileCode, Bookmark, Tag, Image, Paperclip,
  // Finance
  DollarSign, Euro, CreditCard, Banknote, Coins, Wallet, PiggyBank, BadgeDollarSign, Receipt,
  // Food & beverage
  Coffee, Pizza, Apple, Utensils, Wine, Beer, Cookie, Carrot, Sandwich, IceCreamCone, Cake,
  // Gaming
  Gamepad2, Sword, Target, Trophy, Puzzle, Joystick, Crown, Dice1, Dice5, Flag,
  // Home
  Sofa, Lamp, Bed, Fan, Thermometer, UtensilsCrossed,
  // Layout
  LayoutDashboard, LayoutGrid, LayoutList, LayoutTemplate, PanelLeft, PanelRight, Columns2, Grid3X3, Table,
  // Mail
  MailOpen, MailCheck, Inbox,
  // Mathematics
  Plus, Minus, Divide, Equal, Pi, Infinity, Calculator, Binary,
  // Medical
  Stethoscope, Pill, Syringe, HeartPulse, Brain, Microscope, Bandage, Dna,
  // Multimedia
  Play, Pause, FastForward, Rewind, Volume2, VolumeX, Music, Video, Camera, Film, Radio,
  // Nature
  Leaf, Sun, Moon, Cloud, Droplets, Mountain, Wind, Sprout, TreePine, Flower2, Waves,
  // Navigation
  Map, MapPin, Navigation, Navigation2, Compass, Route, LocateFixed, Milestone,
  // Notification
  BellRing, BellOff, AlertCircle, AlertTriangle, Info, BadgeAlert, BadgeCheck,
  // People
  User, Users, UserPlus, UserMinus, UserCheck, UserX, UserCog, Baby, GraduationCap,
  // Photography
  Aperture, Sliders, SlidersHorizontal,
  // Science
  Atom, FlaskConical, Magnet, Orbit, Telescope,
  // Seasons
  Snowflake, Flame, Rainbow, Umbrella,
  // Shapes
  Circle, Square, Triangle, Hexagon, Diamond, Octagon,
  // Shopping
  ShoppingCart, ShoppingBag, Package, Barcode, Gift,
  // Sports
  Medal, Bike, Dumbbell, Footprints, Timer,
  // Sustainability
  Recycle, Battery, BatteryCharging,
  // Text formatting
  Bold, Italic, Underline, Strikethrough, AlignLeft, AlignCenter, AlignRight, AlignJustify, List, ListOrdered, Quote, Heading1, Type,
  // Time & calendar
  Calendar, Clock, AlarmClock, CalendarDays, CalendarCheck, CalendarX, Hourglass, CalendarPlus,
  // Tools
  Wrench, Hammer, PocketKnife, Settings, Settings2, Cog,
  // Transportation
  Car, Truck, Bus, Train, Plane, Ship, Anchor, Rocket, Fuel,
  // Travel
  Luggage, Backpack, Ticket,
  // Weather
  CloudRain, CloudSnow, CloudLightning,
  // Fingerprint / Security extras
  Fingerprint,
  type LucideIcon,
} from 'lucide-react';

export interface IconOption {
  name: string;
  Icon: LucideIcon;
}

export interface IconCategory {
  id: string;
  label: string;
  icons: IconOption[];
}

export const ICON_CATEGORIES: IconCategory[] = [
  {
    id: 'accessibility',
    label: 'Accessibility',
    icons: [
      { name: 'Accessibility', Icon: Accessibility },
      { name: 'Eye', Icon: Eye },
      { name: 'EyeOff', Icon: EyeOff },
      { name: 'Hand', Icon: Hand },
      { name: 'Ear', Icon: Ear },
      { name: 'MousePointer', Icon: MousePointer },
      { name: 'Pointer', Icon: Pointer },
      { name: 'PersonStanding', Icon: PersonStanding },
      { name: 'Move', Icon: Move },
      { name: 'ZoomIn', Icon: ZoomIn },
      { name: 'ZoomOut', Icon: ZoomOut },
    ],
  },
  {
    id: 'accounts',
    label: 'Accounts & access',
    icons: [
      { name: 'Key', Icon: Key },
      { name: 'Lock', Icon: Lock },
      { name: 'LockOpen', Icon: LockOpen },
      { name: 'Shield', Icon: Shield },
      { name: 'ShieldCheck', Icon: ShieldCheck },
      { name: 'ShieldAlert', Icon: ShieldAlert },
      { name: 'ShieldX', Icon: ShieldX },
      { name: 'LogIn', Icon: LogIn },
      { name: 'LogOut', Icon: LogOut },
      { name: 'Fingerprint', Icon: Fingerprint },
      { name: 'KeyRound', Icon: KeyRound },
      { name: 'Scan', Icon: Scan },
    ],
  },
  {
    id: 'animals',
    label: 'Animals',
    icons: [
      { name: 'Bird', Icon: Bird },
      { name: 'Cat', Icon: Cat },
      { name: 'Dog', Icon: Dog },
      { name: 'Fish', Icon: Fish },
      { name: 'Rabbit', Icon: Rabbit },
      { name: 'Bug', Icon: Bug },
      { name: 'Turtle', Icon: Turtle },
      { name: 'Snail', Icon: Snail },
      { name: 'Squirrel', Icon: Squirrel },
      { name: 'Worm', Icon: Worm },
    ],
  },
  {
    id: 'arrows',
    label: 'Arrows',
    icons: [
      { name: 'ArrowUp', Icon: ArrowUp },
      { name: 'ArrowDown', Icon: ArrowDown },
      { name: 'ArrowLeft', Icon: ArrowLeft },
      { name: 'ArrowRight', Icon: ArrowRight },
      { name: 'ArrowUpRight', Icon: ArrowUpRight },
      { name: 'ArrowDownLeft', Icon: ArrowDownLeft },
      { name: 'ArrowLeftRight', Icon: ArrowLeftRight },
      { name: 'ArrowUpDown', Icon: ArrowUpDown },
      { name: 'RotateCw', Icon: RotateCw },
      { name: 'RefreshCw', Icon: RefreshCw },
      { name: 'ChevronsUp', Icon: ChevronsUp },
      { name: 'ChevronsDown', Icon: ChevronsDown },
      { name: 'ChevronUp', Icon: ChevronUp },
      { name: 'ChevronDown', Icon: ChevronDown },
    ],
  },
  {
    id: 'buildings',
    label: 'Buildings',
    icons: [
      { name: 'Building', Icon: Building },
      { name: 'Building2', Icon: Building2 },
      { name: 'School', Icon: School },
      { name: 'Hospital', Icon: Hospital },
      { name: 'Warehouse', Icon: Warehouse },
      { name: 'Factory', Icon: Factory },
      { name: 'Store', Icon: Store },
      { name: 'Landmark', Icon: Landmark },
      { name: 'Home', Icon: Home },
      { name: 'Castle', Icon: Castle },
      { name: 'Church', Icon: Church },
      { name: 'Tent', Icon: Tent },
    ],
  },
  {
    id: 'charts',
    label: 'Charts',
    icons: [
      { name: 'BarChart3', Icon: BarChart3 },
      { name: 'PieChart', Icon: PieChart },
      { name: 'TrendingUp', Icon: TrendingUp },
      { name: 'TrendingDown', Icon: TrendingDown },
      { name: 'Activity', Icon: Activity },
      { name: 'LineChart', Icon: LineChart },
      { name: 'Sigma', Icon: Sigma },
      { name: 'Percent', Icon: Percent },
      { name: 'Hash', Icon: Hash },
    ],
  },
  {
    id: 'communication',
    label: 'Communication',
    icons: [
      { name: 'MessageSquare', Icon: MessageSquare },
      { name: 'MessageCircle', Icon: MessageCircle },
      { name: 'Mail', Icon: Mail },
      { name: 'Phone', Icon: Phone },
      { name: 'PhoneCall', Icon: PhoneCall },
      { name: 'Send', Icon: Send },
      { name: 'Bell', Icon: Bell },
      { name: 'Megaphone', Icon: Megaphone },
      { name: 'Mic', Icon: Mic },
      { name: 'Globe', Icon: Globe },
      { name: 'Link', Icon: Link },
      { name: 'AtSign', Icon: AtSign },
    ],
  },
  {
    id: 'connectivity',
    label: 'Connectivity',
    icons: [
      { name: 'Wifi', Icon: Wifi },
      { name: 'WifiOff', Icon: WifiOff },
      { name: 'Bluetooth', Icon: Bluetooth },
      { name: 'BluetoothConnected', Icon: BluetoothConnected },
      { name: 'Signal', Icon: Signal },
      { name: 'Router', Icon: Router },
      { name: 'Nfc', Icon: Nfc },
      { name: 'Share2', Icon: Share2 },
    ],
  },
  {
    id: 'cursors',
    label: 'Cursors',
    icons: [
      { name: 'MousePointer', Icon: MousePointer },
      { name: 'MousePointer2', Icon: MousePointer2 },
      { name: 'Crosshair', Icon: Crosshair },
      { name: 'Pointer', Icon: Pointer },
      { name: 'Move', Icon: Move },
      { name: 'Hand', Icon: Hand },
      { name: 'Grab', Icon: Grab },
    ],
  },
  {
    id: 'design',
    label: 'Design',
    icons: [
      { name: 'Palette', Icon: Palette },
      { name: 'Paintbrush', Icon: Paintbrush },
      { name: 'Pen', Icon: Pen },
      { name: 'PenTool', Icon: PenTool },
      { name: 'Pencil', Icon: Pencil },
      { name: 'Scissors', Icon: Scissors },
      { name: 'Ruler', Icon: Ruler },
      { name: 'Layers', Icon: Layers },
      { name: 'Wand2', Icon: Wand2 },
      { name: 'Eraser', Icon: Eraser },
      { name: 'Pipette', Icon: Pipette },
      { name: 'Crop', Icon: Crop },
    ],
  },
  {
    id: 'coding',
    label: 'Coding & development',
    icons: [
      { name: 'Code', Icon: Code },
      { name: 'Code2', Icon: Code2 },
      { name: 'Terminal', Icon: Terminal },
      { name: 'GitBranch', Icon: GitBranch },
      { name: 'GitCommit', Icon: GitCommit },
      { name: 'GitMerge', Icon: GitMerge },
      { name: 'GitPullRequest', Icon: GitPullRequest },
      { name: 'Bug', Icon: Bug },
      { name: 'Webhook', Icon: Webhook },
      { name: 'Database', Icon: Database },
      { name: 'Server', Icon: Server },
      { name: 'Braces', Icon: Braces },
      { name: 'PackageOpen', Icon: PackageOpen },
    ],
  },
  {
    id: 'devices',
    label: 'Devices',
    icons: [
      { name: 'Smartphone', Icon: Smartphone },
      { name: 'Tablet', Icon: Tablet },
      { name: 'Laptop', Icon: Laptop },
      { name: 'Monitor', Icon: Monitor },
      { name: 'Tv', Icon: Tv },
      { name: 'Watch', Icon: Watch },
      { name: 'Headphones', Icon: Headphones },
      { name: 'Keyboard', Icon: Keyboard },
      { name: 'Cpu', Icon: Cpu },
      { name: 'HardDrive', Icon: HardDrive },
      { name: 'Printer', Icon: Printer },
    ],
  },
  {
    id: 'emoji',
    label: 'Emoji',
    icons: [
      { name: 'Smile', Icon: Smile },
      { name: 'Frown', Icon: Frown },
      { name: 'Meh', Icon: Meh },
      { name: 'ThumbsUp', Icon: ThumbsUp },
      { name: 'ThumbsDown', Icon: ThumbsDown },
      { name: 'Heart', Icon: Heart },
      { name: 'Star', Icon: Star },
      { name: 'Zap', Icon: Zap },
    ],
  },
  {
    id: 'files',
    label: 'File icons',
    icons: [
      { name: 'File', Icon: File },
      { name: 'FileText', Icon: FileText },
      { name: 'FileCode', Icon: FileCode },
      { name: 'Folder', Icon: Folder },
      { name: 'FolderOpen', Icon: FolderOpen },
      { name: 'Archive', Icon: Archive },
      { name: 'Paperclip', Icon: Paperclip },
      { name: 'Bookmark', Icon: Bookmark },
      { name: 'Tag', Icon: Tag },
      { name: 'Image', Icon: Image },
    ],
  },
  {
    id: 'finance',
    label: 'Finance',
    icons: [
      { name: 'DollarSign', Icon: DollarSign },
      { name: 'Euro', Icon: Euro },
      { name: 'CreditCard', Icon: CreditCard },
      { name: 'Banknote', Icon: Banknote },
      { name: 'Coins', Icon: Coins },
      { name: 'Wallet', Icon: Wallet },
      { name: 'PiggyBank', Icon: PiggyBank },
      { name: 'BadgeDollarSign', Icon: BadgeDollarSign },
      { name: 'Receipt', Icon: Receipt },
      { name: 'TrendingUp', Icon: TrendingUp },
    ],
  },
  {
    id: 'food',
    label: 'Food & beverage',
    icons: [
      { name: 'Coffee', Icon: Coffee },
      { name: 'Pizza', Icon: Pizza },
      { name: 'Apple', Icon: Apple },
      { name: 'Utensils', Icon: Utensils },
      { name: 'Wine', Icon: Wine },
      { name: 'Beer', Icon: Beer },
      { name: 'Cookie', Icon: Cookie },
      { name: 'Carrot', Icon: Carrot },
      { name: 'Sandwich', Icon: Sandwich },
      { name: 'IceCreamCone', Icon: IceCreamCone },
      { name: 'Cake', Icon: Cake },
    ],
  },
  {
    id: 'gaming',
    label: 'Gaming',
    icons: [
      { name: 'Gamepad2', Icon: Gamepad2 },
      { name: 'Sword', Icon: Sword },
      { name: 'Target', Icon: Target },
      { name: 'Trophy', Icon: Trophy },
      { name: 'Puzzle', Icon: Puzzle },
      { name: 'Joystick', Icon: Joystick },
      { name: 'Crown', Icon: Crown },
      { name: 'Dice1', Icon: Dice1 },
      { name: 'Dice5', Icon: Dice5 },
      { name: 'Flag', Icon: Flag },
    ],
  },
  {
    id: 'home',
    label: 'Home',
    icons: [
      { name: 'Home', Icon: Home },
      { name: 'Sofa', Icon: Sofa },
      { name: 'Lamp', Icon: Lamp },
      { name: 'Bed', Icon: Bed },
      { name: 'Fan', Icon: Fan },
      { name: 'Thermometer', Icon: Thermometer },
      { name: 'UtensilsCrossed', Icon: UtensilsCrossed },
      { name: 'Tv', Icon: Tv },
    ],
  },
  {
    id: 'layout',
    label: 'Layout',
    icons: [
      { name: 'LayoutDashboard', Icon: LayoutDashboard },
      { name: 'LayoutGrid', Icon: LayoutGrid },
      { name: 'LayoutList', Icon: LayoutList },
      { name: 'LayoutTemplate', Icon: LayoutTemplate },
      { name: 'PanelLeft', Icon: PanelLeft },
      { name: 'PanelRight', Icon: PanelRight },
      { name: 'Columns2', Icon: Columns2 },
      { name: 'Grid3X3', Icon: Grid3X3 },
      { name: 'Table', Icon: Table },
    ],
  },
  {
    id: 'mail',
    label: 'Mail',
    icons: [
      { name: 'Mail', Icon: Mail },
      { name: 'MailOpen', Icon: MailOpen },
      { name: 'MailCheck', Icon: MailCheck },
      { name: 'Send', Icon: Send },
      { name: 'Inbox', Icon: Inbox },
      { name: 'AtSign', Icon: AtSign },
      { name: 'Bell', Icon: Bell },
    ],
  },
  {
    id: 'math',
    label: 'Mathematics',
    icons: [
      { name: 'Plus', Icon: Plus },
      { name: 'Minus', Icon: Minus },
      { name: 'Divide', Icon: Divide },
      { name: 'Equal', Icon: Equal },
      { name: 'Percent', Icon: Percent },
      { name: 'Pi', Icon: Pi },
      { name: 'Sigma', Icon: Sigma },
      { name: 'Infinity', Icon: Infinity },
      { name: 'Calculator', Icon: Calculator },
      { name: 'Binary', Icon: Binary },
      { name: 'Hash', Icon: Hash },
    ],
  },
  {
    id: 'medical',
    label: 'Medical',
    icons: [
      { name: 'Stethoscope', Icon: Stethoscope },
      { name: 'Pill', Icon: Pill },
      { name: 'Syringe', Icon: Syringe },
      { name: 'HeartPulse', Icon: HeartPulse },
      { name: 'Brain', Icon: Brain },
      { name: 'Microscope', Icon: Microscope },
      { name: 'Bandage', Icon: Bandage },
      { name: 'Dna', Icon: Dna },
      { name: 'Heart', Icon: Heart },
      { name: 'Activity', Icon: Activity },
    ],
  },
  {
    id: 'multimedia',
    label: 'Multimedia',
    icons: [
      { name: 'Play', Icon: Play },
      { name: 'Pause', Icon: Pause },
      { name: 'FastForward', Icon: FastForward },
      { name: 'Rewind', Icon: Rewind },
      { name: 'Volume2', Icon: Volume2 },
      { name: 'VolumeX', Icon: VolumeX },
      { name: 'Music', Icon: Music },
      { name: 'Video', Icon: Video },
      { name: 'Camera', Icon: Camera },
      { name: 'Film', Icon: Film },
      { name: 'Radio', Icon: Radio },
      { name: 'Headphones', Icon: Headphones },
    ],
  },
  {
    id: 'nature',
    label: 'Nature',
    icons: [
      { name: 'Leaf', Icon: Leaf },
      { name: 'Sun', Icon: Sun },
      { name: 'Moon', Icon: Moon },
      { name: 'Cloud', Icon: Cloud },
      { name: 'Droplets', Icon: Droplets },
      { name: 'Mountain', Icon: Mountain },
      { name: 'Wind', Icon: Wind },
      { name: 'Sprout', Icon: Sprout },
      { name: 'TreePine', Icon: TreePine },
      { name: 'Flower2', Icon: Flower2 },
      { name: 'Waves', Icon: Waves },
    ],
  },
  {
    id: 'navigation',
    label: 'Navigation & Maps',
    icons: [
      { name: 'Map', Icon: Map },
      { name: 'MapPin', Icon: MapPin },
      { name: 'Navigation', Icon: Navigation },
      { name: 'Navigation2', Icon: Navigation2 },
      { name: 'Compass', Icon: Compass },
      { name: 'Route', Icon: Route },
      { name: 'LocateFixed', Icon: LocateFixed },
      { name: 'Milestone', Icon: Milestone },
      { name: 'Crosshair', Icon: Crosshair },
      { name: 'Globe', Icon: Globe },
    ],
  },
  {
    id: 'notification',
    label: 'Notification',
    icons: [
      { name: 'Bell', Icon: Bell },
      { name: 'BellRing', Icon: BellRing },
      { name: 'BellOff', Icon: BellOff },
      { name: 'AlertCircle', Icon: AlertCircle },
      { name: 'AlertTriangle', Icon: AlertTriangle },
      { name: 'Info', Icon: Info },
      { name: 'BadgeAlert', Icon: BadgeAlert },
      { name: 'BadgeCheck', Icon: BadgeCheck },
      { name: 'Megaphone', Icon: Megaphone },
    ],
  },
  {
    id: 'people',
    label: 'People',
    icons: [
      { name: 'User', Icon: User },
      { name: 'Users', Icon: Users },
      { name: 'UserPlus', Icon: UserPlus },
      { name: 'UserMinus', Icon: UserMinus },
      { name: 'UserCheck', Icon: UserCheck },
      { name: 'UserX', Icon: UserX },
      { name: 'UserCog', Icon: UserCog },
      { name: 'Baby', Icon: Baby },
      { name: 'Crown', Icon: Crown },
      { name: 'GraduationCap', Icon: GraduationCap },
      { name: 'PersonStanding', Icon: PersonStanding },
    ],
  },
  {
    id: 'photography',
    label: 'Photography',
    icons: [
      { name: 'Camera', Icon: Camera },
      { name: 'Aperture', Icon: Aperture },
      { name: 'Sliders', Icon: Sliders },
      { name: 'SlidersHorizontal', Icon: SlidersHorizontal },
      { name: 'ZoomIn', Icon: ZoomIn },
      { name: 'ZoomOut', Icon: ZoomOut },
      { name: 'Crop', Icon: Crop },
      { name: 'Image', Icon: Image },
      { name: 'Film', Icon: Film },
    ],
  },
  {
    id: 'science',
    label: 'Science',
    icons: [
      { name: 'Atom', Icon: Atom },
      { name: 'FlaskConical', Icon: FlaskConical },
      { name: 'Magnet', Icon: Magnet },
      { name: 'Orbit', Icon: Orbit },
      { name: 'Telescope', Icon: Telescope },
      { name: 'Microscope', Icon: Microscope },
      { name: 'Dna', Icon: Dna },
      { name: 'Binary', Icon: Binary },
      { name: 'Zap', Icon: Zap },
    ],
  },
  {
    id: 'seasons',
    label: 'Seasons',
    icons: [
      { name: 'Sun', Icon: Sun },
      { name: 'Snowflake', Icon: Snowflake },
      { name: 'Leaf', Icon: Leaf },
      { name: 'Flower2', Icon: Flower2 },
      { name: 'Wind', Icon: Wind },
      { name: 'Cloud', Icon: Cloud },
      { name: 'Umbrella', Icon: Umbrella },
      { name: 'Flame', Icon: Flame },
      { name: 'Rainbow', Icon: Rainbow },
    ],
  },
  {
    id: 'security',
    label: 'Security',
    icons: [
      { name: 'Shield', Icon: Shield },
      { name: 'ShieldCheck', Icon: ShieldCheck },
      { name: 'ShieldAlert', Icon: ShieldAlert },
      { name: 'ShieldX', Icon: ShieldX },
      { name: 'Lock', Icon: Lock },
      { name: 'LockOpen', Icon: LockOpen },
      { name: 'Key', Icon: Key },
      { name: 'KeyRound', Icon: KeyRound },
      { name: 'Eye', Icon: Eye },
      { name: 'EyeOff', Icon: EyeOff },
      { name: 'Fingerprint', Icon: Fingerprint },
      { name: 'Scan', Icon: Scan },
    ],
  },
  {
    id: 'shapes',
    label: 'Shapes',
    icons: [
      { name: 'Circle', Icon: Circle },
      { name: 'Square', Icon: Square },
      { name: 'Triangle', Icon: Triangle },
      { name: 'Hexagon', Icon: Hexagon },
      { name: 'Diamond', Icon: Diamond },
      { name: 'Octagon', Icon: Octagon },
      { name: 'Star', Icon: Star },
      { name: 'Heart', Icon: Heart },
    ],
  },
  {
    id: 'shopping',
    label: 'Shopping',
    icons: [
      { name: 'ShoppingCart', Icon: ShoppingCart },
      { name: 'ShoppingBag', Icon: ShoppingBag },
      { name: 'Package', Icon: Package },
      { name: 'Barcode', Icon: Barcode },
      { name: 'Gift', Icon: Gift },
      { name: 'Store', Icon: Store },
      { name: 'Wallet', Icon: Wallet },
      { name: 'CreditCard', Icon: CreditCard },
      { name: 'Receipt', Icon: Receipt },
      { name: 'Tag', Icon: Tag },
    ],
  },
  {
    id: 'social',
    label: 'Social',
    icons: [
      { name: 'Share2', Icon: Share2 },
      { name: 'MessageCircle', Icon: MessageCircle },
      { name: 'Heart', Icon: Heart },
      { name: 'ThumbsUp', Icon: ThumbsUp },
      { name: 'ThumbsDown', Icon: ThumbsDown },
      { name: 'Users', Icon: Users },
      { name: 'Globe', Icon: Globe },
      { name: 'Hash', Icon: Hash },
      { name: 'AtSign', Icon: AtSign },
      { name: 'Link', Icon: Link },
    ],
  },
  {
    id: 'sports',
    label: 'Sports',
    icons: [
      { name: 'Trophy', Icon: Trophy },
      { name: 'Medal', Icon: Medal },
      { name: 'Bike', Icon: Bike },
      { name: 'Dumbbell', Icon: Dumbbell },
      { name: 'Target', Icon: Target },
      { name: 'Flag', Icon: Flag },
      { name: 'Mountain', Icon: Mountain },
      { name: 'Footprints', Icon: Footprints },
      { name: 'Timer', Icon: Timer },
    ],
  },
  {
    id: 'sustainability',
    label: 'Sustainability',
    icons: [
      { name: 'Leaf', Icon: Leaf },
      { name: 'Recycle', Icon: Recycle },
      { name: 'Sun', Icon: Sun },
      { name: 'Wind', Icon: Wind },
      { name: 'Droplets', Icon: Droplets },
      { name: 'Sprout', Icon: Sprout },
      { name: 'TreePine', Icon: TreePine },
      { name: 'Battery', Icon: Battery },
      { name: 'BatteryCharging', Icon: BatteryCharging },
      { name: 'Globe', Icon: Globe },
      { name: 'Zap', Icon: Zap },
    ],
  },
  {
    id: 'textFormatting',
    label: 'Text formatting',
    icons: [
      { name: 'Bold', Icon: Bold },
      { name: 'Italic', Icon: Italic },
      { name: 'Underline', Icon: Underline },
      { name: 'Strikethrough', Icon: Strikethrough },
      { name: 'AlignLeft', Icon: AlignLeft },
      { name: 'AlignCenter', Icon: AlignCenter },
      { name: 'AlignRight', Icon: AlignRight },
      { name: 'AlignJustify', Icon: AlignJustify },
      { name: 'List', Icon: List },
      { name: 'ListOrdered', Icon: ListOrdered },
      { name: 'Quote', Icon: Quote },
      { name: 'Heading1', Icon: Heading1 },
      { name: 'Type', Icon: Type },
    ],
  },
  {
    id: 'time',
    label: 'Time & calendar',
    icons: [
      { name: 'Calendar', Icon: Calendar },
      { name: 'Clock', Icon: Clock },
      { name: 'AlarmClock', Icon: AlarmClock },
      { name: 'Timer', Icon: Timer },
      { name: 'CalendarDays', Icon: CalendarDays },
      { name: 'CalendarCheck', Icon: CalendarCheck },
      { name: 'CalendarX', Icon: CalendarX },
      { name: 'Hourglass', Icon: Hourglass },
      { name: 'Watch', Icon: Watch },
      { name: 'CalendarPlus', Icon: CalendarPlus },
    ],
  },
  {
    id: 'tools',
    label: 'Tools',
    icons: [
      { name: 'Wrench', Icon: Wrench },
      { name: 'Hammer', Icon: Hammer },
      { name: 'PocketKnife', Icon: PocketKnife },
      { name: 'Settings', Icon: Settings },
      { name: 'Settings2', Icon: Settings2 },
      { name: 'Scissors', Icon: Scissors },
      { name: 'Ruler', Icon: Ruler },
      { name: 'Cog', Icon: Cog },
      { name: 'Zap', Icon: Zap },
    ],
  },
  {
    id: 'transportation',
    label: 'Transportation',
    icons: [
      { name: 'Car', Icon: Car },
      { name: 'Truck', Icon: Truck },
      { name: 'Bus', Icon: Bus },
      { name: 'Train', Icon: Train },
      { name: 'Plane', Icon: Plane },
      { name: 'Ship', Icon: Ship },
      { name: 'Bike', Icon: Bike },
      { name: 'Anchor', Icon: Anchor },
      { name: 'Rocket', Icon: Rocket },
      { name: 'Fuel', Icon: Fuel },
    ],
  },
  {
    id: 'travel',
    label: 'Travel',
    icons: [
      { name: 'Map', Icon: Map },
      { name: 'MapPin', Icon: MapPin },
      { name: 'Luggage', Icon: Luggage },
      { name: 'Backpack', Icon: Backpack },
      { name: 'Ticket', Icon: Ticket },
      { name: 'Globe', Icon: Globe },
      { name: 'Compass', Icon: Compass },
      { name: 'Plane', Icon: Plane },
      { name: 'Camera', Icon: Camera },
      { name: 'Tent', Icon: Tent },
    ],
  },
  {
    id: 'weather',
    label: 'Weather',
    icons: [
      { name: 'Sun', Icon: Sun },
      { name: 'Cloud', Icon: Cloud },
      { name: 'CloudRain', Icon: CloudRain },
      { name: 'CloudSnow', Icon: CloudSnow },
      { name: 'CloudLightning', Icon: CloudLightning },
      { name: 'Wind', Icon: Wind },
      { name: 'Thermometer', Icon: Thermometer },
      { name: 'Umbrella', Icon: Umbrella },
      { name: 'Rainbow', Icon: Rainbow },
      { name: 'Snowflake', Icon: Snowflake },
      { name: 'Moon', Icon: Moon },
      { name: 'Flame', Icon: Flame },
    ],
  },
];

export const ICON_OPTIONS: IconOption[] = ICON_CATEGORIES.flatMap((c) => c.icons);

const ICON_MAP: Record<string, LucideIcon> = Object.fromEntries(
  ICON_OPTIONS.map(({ name, Icon }) => [name, Icon])
);

export function getIconByName(name: string): LucideIcon {
  return ICON_MAP[name] ?? Type;
}
